routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

	
// Route::get('find', 'SearchController@find');
// Route::get('view', 'SearchController@view');
// Route::get('customer/{id}', function($id) {
//    $customer = App\Models\Admin\Customers::find($id);
//    return $customer->name . '@' . $customer->phone . '-' . $customer->address;
// });

// Route::get('autocomplete', 'SearchController@autocomplete');

Route::get('customer/{id}', function() {
   $customer = Customer::find($id);
   return $customer->name . '@' . $customer->phone . '-' . $customer->address;
});

Auth::routes();
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');


// Route::get('/home', 'HomeController@index')->name('home');

// Route::get('/', function () {
//     return view('layouts.index');
// });

	
// Admin
	Route::resource('categories_admin', 'Admin\Categories_AdminController');
	Route::resource('brand_admin', 'Admin\Brand_AdminController');
	Route::resource('status_admin', 'Admin\Status_AdminController');
	Route::resource('bill_admin', 'Admin\AdminBillController');
	Route::resource('user_admin', 'Admin\AdminUserController');
	Route::get('user_search_admin', 'Admin\AdminUserController@search')->name('user_search_admin');
	Route::get('userBlock_admin/{product_id}', 'Admin\AdminUserController@block')->name('userBlock_admin');
	Route::resource('profit', 'Admin\ProfitController');
	Route::get('invoice', 'Admin\ProfitController@invoice')->name('invoice');

	
	Route::resource('admin', 'Admin\DefaultController');
	Route::resource('status', 'StatusController');


	Route::resource('product_admin', 'Admin\Admin_ProductControlelr');
	Route::get('product_search_admin', 'Admin\Admin_ProductControlelr@search')->name('product_search_admin');
	Route::resource('shop_admin', 'Admin\AdminShopController');
	Route::get('shop_search_admin', 'Admin\AdminShopController@search')->name('shop_search_admin');
	Route::get('shop_admin_pay', 'Admin\AdminShopController@pay')->name('shop_admin_pay');
	Route::get('register_shop', 'Admin\AdminShopController@registerShop')->name('register_shop');
	Route::get('register_shop_details/{id}', 'Admin\AdminShopController@register_shop_details')->name('register_shop_details');
	Route::get('register_shop_update/{id}', 'Admin\AdminShopController@register_shop_update')->name('register_shop_update');
	Route::get('register_shop_destroy/{id}', 'Admin\AdminShopController@register_shop_destroy')->name('register_shop_destroy');


/*USER*/
	// USER
	Route::resource('user', 'UserController');
	Route::get('click/{email}', 'UserController@click')->name('click');
	Route::get('user_personalinformation/{id}', 'UserController@user_personalinformation')->name('user_personalinformation');
	Route::get('user_edit/{id}', 'UserController@user_personalinformation_edit')->name('user_edit');
	Route::PATCH('user_update/{id}', 'UserController@user_update')->name('user_update');

	Route::get('order', 'UserController@order')->name('order');
	Route::get('order_details/{id}', 'UserController@details')->name('order_details');

	Route::get('pay/{id}', 'UserController@pay')->name('pay');

	// SHOP
	Route::get('shop/{id}', 'UserController@shop')->name('shop');
	Route::get('shop_edit/{id}', 'UserController@shop_edit')->name('shop_edit');
	Route::get('shop_update/{id}', 'UserController@shop_update')->name('shop_update');
	Route::get('buy_post', 'UserController@buypost')->name('buy_post');
	Route::get('buy', 'UserController@buy')->name('buy');

	Route::resource('shop', 'ShopController');
	// PRODUCT
	Route::resource('product', 'ProductController');
	Route::get('star/{star}/{id}', 'ProductController@star')->name('star');
	Route::get('product_delete/{product_id}', 'ProductController@delete')->name('product_delete');
	Route::get('product_status/{product_id}/{status_id}', 'ProductController@status')->name('product_status');
	Route::get('product_search/{id}', 'ProductController@search')->name('product_search');
	//EXCHANGE
	Route::get('product_exchange', 'ProductController@exchange')->name('product_exchange');
	Route::get('month', 'ProductController@month')->name('month');

	Route::resource('comments', 'CommentController');
	Route::post('update_2/{cmt_id}/{product_id}', 'CommentController@update_2')->name('update_2');

	
/*RATE*/
	Route::resource('home', 'HomeController');
	Route::get('product_shop/{shop_id}', 'HomeController@product_shop')->name('product_shop');

	Route::get('search', 'HomeController@search')->name('search');

	Route::get('rate_high', 'HomeController@getRate_High')->name('rate_high');
	Route::get('rate_low', 'HomeController@getRate_Low')->name('rate_low');
	Route::get('rate_name', 'HomeController@getRate_Name')->name('rate_name');

/*CART*/
	Route::get('create_cart/{product_id}', 'CartController@create')->name('create_cart');
	Route::get('index/{product_id}', 'CartController@createIndex')->name('index');
	Route::get('cart', 'CartController@cart')->name('cart');
	Route::get('delete_cart/{id}', 'CartController@delete')->name('delete_cart');
	Route::get('deleteall_cart', 'CartController@deleteall')->name('deleteall_cart');
	// Route::post('update_cart/{id}/{increment}', 'CartController@update')->name('update_cart');
	Route::post('update_cart/{id}', 'CartController@update')->name('update_cart');
	Route::post('code_input/{id}', 'CartController@code')->name('code_input');

/*CHECKOUT*/
	Route::get('checkout/{id}', 'CartController@getCheckOut')->name('checkout');
	Route::post('post_checkout', 'CartController@postCheckOut')->name('post_checkout');
	Route::post('post_checkout_id/{id}', 'CartController@postCheckOut_id')->name('post_checkout_id');
	Route::post('post_checkout_code_id/{id}/{number}', 'CartController@postCheckOut_code_id')->name('post_checkout_code_id');


/*CATEGORIES*/
	Route::resource('categories', 'CategoriesController');

	/*ASIDE*/
	Route::get('categories_price/{categories_id}/{price1}/{price2}', 'CategoriesController@getCategories_Price')->name('categories_price');
	Route::get('categories_brand/{categories_id}/{brand_id}', 'CategoriesController@getCategorie_Brand')->name('categories_brand');
	Route::get('categories_price_brand/{categories_id}/{price1}/{price2}/{brand_id}', 'CategoriesController@getCategories_Price_Brand')->name('categories_price_brand');

	/*RATE: general*/
	Route::get('categories_rate_high/{categories_id}', 'CategoriesController@getCategories_RateHigh')->name('categories_ratehigh');
	Route::get('categories_rate_low/{categories_id}', 'CategoriesController@getCategories_RateLow')->name('categories_ratelow');
	Route::get('categories_rate_name/{categories_id}', 'CategoriesController@getCategories_RateName')->name('categories_ratename');

	/*RATE: price. no brand_id*/
	Route::get('categories_price_rate_high/{categories_id}/{price1}/{price2}', 'CategoriesController@getCategories_PriceRateHigh')->name('categories_price_ratehigh');
	Route::get('categories_price_rate_low/{categories_id}/{price1}/{price2}', 'CategoriesController@getCategories_PriceRateLow')->name('categories_price_ratelow');
	Route::get('categories_price_rate_name/{categories_id}/{price1}/{price2}', 'CategoriesController@getCategories_PriceRateName')->name('categories_price_ratename');

	/*RATE: no price. brand_id*/
	Route::get('categories_brand_rate_high/{categories_id}/{brand_id}', 'CategoriesController@getCategories_BrandRateHigh')->name('categories_brand_ratehigh');
	Route::get('categories_brand_rate_low/{categories_id}/{brand_id}', 'CategoriesController@getCategories_BrandRateLow')->name('categories_brand_ratelow');
	Route::get('categories_brand_rate_name/{categories_id}/{brand_id}', 'CategoriesController@getCategories_BrandRateName')->name('categories_brand_ratename');

	/*RATE: price. brand_id*/
	Route::get('categories_price_brand_rate_high/{categories_id}/{price1}/{price2}/{brand_id}', 'CategoriesController@getCategories_Price_BrandRateHigh')->name('categories_price_brand_ratehigh');
	Route::get('categories_price_brand_rate_low/{categories_id}/{price1}/{price2}/{brand_id}', 'CategoriesController@getCategorie_Price_BrandRateLow')->name('categories_price_brand_ratelow');
	Route::get('categories_price_brand_rate_name/{categories_id}/{price1}/{price2}/{brand_id}', 'CategoriesController@getCategories_Price_BrandRateName')->name('categories_price_brand_ratename');



/*BRAND*/
	Route::resource('brand', 'BrandController');

	/*ASIDE*/
	Route::get('brand_price/{brand_id}/{price1}/{price2}', 'BrandController@getBrand_Price')->name('brand_price');
	Route::get('brand_categories/{brand_id}/{categories_id}', 'BrandController@getBrand_Categories')->name('brand_categories');
	Route::get('brand_price_categories/{brand_id}/{price1}/{price2}/{categories_id}', 'BrandController@getBrand_Price_Categories')->name('brand_price_categories');

	/*RATE: general*/
	Route::get('brand_rate_high/{brand_id}', 'BrandController@getBrand_RateHigh')->name('brand_ratehigh');
	Route::get('brand_rate_low/{brand_id}', 'BrandController@getBrand_RateLow')->name('brand_ratelow');
	Route::get('brand_rate_name/{brand_id}', 'BrandController@getBrand_RateName')->name('brand_ratename');

	/*RATE: price. no categories*/
	Route::get('brand_price_rate_high/{brand_id}/{price1}/{price2}', 'BrandController@getBrand_PriceRateHigh')->name('brand_price_ratehigh');
	Route::get('brand_price_rate_low/{brand_id}/{price1}/{price2}', 'BrandController@getBrand_PriceRateLow')->name('brand_price_ratelow');
	Route::get('brand_price_rate_name/{brand_id}/{price1}/{price2}', 'BrandController@getBrand_PriceRateName')->name('brand_price_ratename');

	/*RATE: no price. categories_id*/

resources/views/cart.blade.php
@extends('inc-index/layout')
<script src="{{asset('js/jquery-3.3.1.min.js')}}"></script>
<style>
table {
    border-collapse: collapse;
    width: 100%;
}

th, td {
    padding: 10px;
    text-align: left;
    border-bottom: 1px solid #ddd;
}

tr:hover {background-color:#f5f5f5;}
</style>
@section('content')
    <!-- Characteristics -->
    
    <div class="single_product">
        <div class="container">
            <div class="row">
                @include('flash::message')
            <div class="col-sm-12">
            
            <!-- /.box-header -->
            <div class="box-body">
                    <div class="cart_container">
                        @if ( Cart::count() == 0 )
                        <div class="notification" style="text-align: center; height: 250px;">
                            <br/> <br/>
                            <h4>Hiện bạn chưa có sản phẩm trong giỏ hàng, vui lòng trở lại trang chủ để tiếp tục mua sắm.</h4>
                                <a href="{{ route('home.index')}}" style="font-size: 25px; color: red;">Trang chủ</a>
                            <br/>
                            <h4>Xin chân thành cảm ơn</h4>
                            <i class="fa fa-thumbs-o-up" style="font-size: 75px;"></i>

                        </div>
                        @else
                        <div class="cart_title">Giỏ Hàng</div>
                        <br>
                        <div class="card">
                        <div class="card-body p-0">
                        <table class="table table-striped">
                          <tbody><tr>
                            <th style="width: 10px">Ảnh</th>
                            <th>Sản Phẩm</th>
                            <th>Số Lượng</th>
                            <th>Giá</th>
                            <th>Tổng </th>
                            <th>Cập Nhật</th>
                            <th style="width: 40px"></th>
                          </tr>
                          <?php  $coupon_code = 0; ?>
                          @foreach($content as $item)
                          <form method="POST" action="{!! route('update_cart',['id'=>$item->rowId]) !!}">
                                        <input type="hidden" name="_token" value="{{csrf_token()}}">
                          <tr>
                            <td><img src=" {{ $item->options->img  }} " alt="" width="150" height="150"></td>
                            <td style="text-align: justify;padding: 70px"><a href="{{ route('product.show',$item->id) }}">{!! $item->name !!}</a></td>
                            <td style="text-align: justify"><input type="number" min="1" name="qty" value="{!! $item->qty !!}" style="margin-top: 59px;width: 3em;"></td>
                            <td style="text-align: justify;"><div style="margin-top: 59px">{!! number_format($item->price, 0, ',', '.') !!} Đ</div></td>
                            <td style="text-align: justify;"><div style="margin-top: 59px">{!! number_format($item->price*$item->qty, 0, ',', '.') !!} Đ
                                                    <?php  $coupon_code = $item->price*$item->qty + $coupon_code;?></div></td>
                            <td style="text-align: justify;">
                                <div style="margin-top: 50px"><button type="submit" class="btn btn-success">Cập nhập</button></div>
                            </td>
                            <td style="text-align: justify;"><div style="margin-top: 50px"><a href="{{ route('delete_cart', ['id' => $item->rowId]) }}" ><img class="tooltip-test" data-original-title="delete"  src="{{ asset('images/remove-icon.png') }}" alt="sad" width="55px" ></a></div></td>
                          </tr>
                          </form>
                          @endforeach
                        </tbody></table>
                        </div>
                        </div>
                        
                        <br>
                        <div style="text-align: right;">
                        <a href="{{ route('deleteall_cart') }}" class="btn btn-primary">Xoá Tất Cả</a>
                        <a href="{{ route('checkout', $item->rowId) }}" class="btn btn-primary"> Đặt Hàng</a>
                        </div>
                        <br>
                        <div align="right">
                           <div class="col-md-4" align="right">
                            <table >
                                <thead>
                                <tr>
                                    <td>Thông tin đơn hàng</td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td>Phí giao hàng</td>
                                    <td>15.000Đ</td>
                                </tr>
                                @if ( Auth::user() ) 
                                           <tr>
                                    {!!  Form::open(array('route' => ['code_input', Auth::id()], 'method' => 'post' )) !!}
                                    <td>
                                        {!! Form::text('code', null, ['class' => 'form-control', 'size'=> "width='20px'", 'placeholder' => 'Nhập mã giảm giá' ])  !!}
                                    </td>
                                    <td>
                                        {!! Form::button('Áp dụng', ['type' => 'submit', 'class' => 'btn btn-success'])  !!}
                                    </td>
                                    {!! Form::close() !!}
                                </tr>
                                @endif
                                    <td >
                                        Giảm giá:
                                    </td>
                                    <td>
                                        @if ( session()->has('key') ) 
                                           10%
                                        @else 
                                            0%
                                        @endif
                                    </td>
                                </tr>
                                <tr>
                                    <td >
                                        Tổng Tiền:
                                    </td>
                                    <td>
                                        @if ( session()->has('key') ) 
                                            <?php  echo number_format($coupon_code*0.9, 0, ',', '.'); ?>Đ
                                        @else
                                            {!! $total !!}Đ
                                        @endif
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                            <div style="width: 400px" align="center">
                    @include('flash::message')        
                </div>
                
                <script>
                $('div.alert').not('.alert-important').delay(3000).fadeOut(350);
                </script>
                {!!  Form::open(array('route' => ['code_input', Auth::id()], 'method' => 'post' )) !!}
                        </div>
                        <br>
                <div class="col-md-10">
                Bạn có {{ $count }} mã giảm giá
                    @foreach ( $codes as $code )
                        : {{ $code->code }}
                    @endforeach
                </div>
                @endif
               <br>     
            <div class="clearfix visible-sm-block"></div>
        </div>
            <!-- /.row -->
    </section>
            <!-- /.content -->
    </div>
    </div>
</div>
</div>

    @endsection
    

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/news.blade.php
@extends('inc-index/layout')
<script src="{{ asset('js/jquery-3.3.1.min.js')}}"></script>
<script src="{{ asset('js/custom.js ')}}"></script>
<link rel="stylesheet" type="text/css" href="{{ asset('styles/regular_styles.css')}}">
<link rel="stylesheet" type="text/css" href="{{ asset('styles/regular_responsive.css')}}">
<style type="text/css">
	ul {
	    list-style-type: number;
	}
</style>

@section('content')
   
<!-- Single Blog Post -->

	<div class="single_post">
		<div class="container">
			<div class="row">
				@if( empty($news_details) )
								@if( $information_id == '{"information_id":1}' )
									<H3>TIN TỨC</H3>
								@elseif ( $information_id == '{"information_id":2}' )
									<H3>GIỚI THIỆU</H3>
								@elseif ( $information_id == '{"information_id":3}' )
									<H3>LIÊN HỆ</H3>
								@else
									<H3>THÔNG TIN TUYỂN DỤNG</H3>
								@endif
					<div class="col-lg-12" style="border: 3px ; border-style: ridge;padding: 20px" >
						<ol style="padding-left: 30px">
							@foreach ( $news as $new )
							  <li style="padding-left: 30px"><h4><a href="{{ route('news_details', $new->id) }}">{!!  $new->title !!}</a></h4></li>
							@endforeach
						</ol>
						@else 
						<div class="col-lg-12" style="border: 3px ; border-style: ridge;padding: 20px">
							@foreach ( $news_details as $new )
							<div class="single_post_title">{!!  $new->title !!}</div>
							<div class="single_post_text">
								{!! $new->news !!}
							</div>
							@endforeach
						</div>
					</div>
				@endif
			</div>
		</div>
	</div>
<br>
<br>
<br>
<br>
<br>
<br>
	@endsection

resources/views/notification.blade.php
@extends('inc-index/layout')
<script src="{{asset('js/jquery-3.3.1.min.js')}}"></script>

@section('content'))

<div class="notification" style="text-align: center; height: 500px; margin-left: 150px; padding-top: 150px; font-size: 16px; margin-right: 150px;">
	<br/> <br/>
	<h4>Bạn đã đặt hàng thành công, chúng tôi sẽ liên lạc với bạn sau 30s. Bạn vui lòng vào gmail của mình đăng kí để xem lại đơn hàng mà bạn đã đặt. Bạn có thể quay lại trang chủ để mua hàng tiếp theo đường link sau: <h4>
		<a href="{{ route('home.index')}}" style="font-size: 25px; color: red;">Trang chủ</a>
	<br/>
	<h4>Xin chân thành cảm ơn</h4>
	<i class="fa fa-thumbs-o-up" style="font-size: 75px;"></i>

</div>



@endsection

resources/views/search.blade.php
@extends('inc-index/layout')
<script src="{{asset('js/jquery-3.3.1.min.js')}}"></script>

<script src="js/jquery-3.3.1.min.js"></script>
<script src="styles/bootstrap4/popper.js"></script>
<script src="styles/bootstrap4/bootstrap.min.js"></script>
<script src="plugins/greensock/TweenMax.min.js"></script>
<script src="plugins/greensock/TimelineMax.min.js"></script>
<script src="plugins/scrollmagic/ScrollMagic.min.js"></script>
<script src="plugins/greensock/animation.gsap.min.js"></script>
<script src="plugins/greensock/ScrollToPlugin.min.js"></script>
<script src="plugins/OwlCarousel2-2.2.1/owl.carousel.js"></script>
<script src="plugins/slick-1.8.0/slick.js"></script>
<script src="plugins/easing/easing.js"></script>
<script src="js/custom.js"></script>

@section('content')
<div class="home">
        <?php $i = ($page->currentpage()-1)* $page->perpage() + 1;?>

	
		<div class="home_background parallax-window" data-parallax="scroll" data-image-src="images/shop_background.jpg"></div>
		<div class="home_overlay"></div>
		<div class="home_content d-flex flex-column align-items-center justify-content-center">
			<h2 class="home_title">Smartphones 	</h2>
		</div>
	</div>

	<!-- Shop -->

	<div class="shop">
		<div class="container">
			<div class="row">
				<div class="col-lg-3">

					<!-- Shop Sidebar -->
					<div class="shop_sidebar">
						<div class="sidebar_section">
							<div class="sidebar_title">Danh Mục</div>
							<ul class="sidebar_categories">
								@foreach ( $categories as $categories )
									<li>
										<a href="{!! route('categories.show', $categories->id  ) !!}">{{ $categories->name }}</a>
									</li>
								@endforeach
							</ul>
						</div>
						
						<div class="sidebar_section">
							<div class="sidebar_subtitle brands_subtitle">Hãng</div>
							<ul class="brands_list">
								@foreach ($brands as $brands)
									<li class="brand"><a href="{!! route('brand.show', $brands->id  ) !!}""> {{ $brands->name }} </a></li>
								@endforeach
							</ul>
						</div>
					</div>

				</div>

				<div class="col-lg-9">
					
					<!-- Shop Content -->

					<div class="shop_content">
						<div class="shop_bar clearfix">
							<div class="shop_product_count"><span> 
                                    {{ $count }}
                                </span> Sản phẩm được tìm thấy theo "{{ $search }}" </div>
							<div class="shop_sorting">
								<span>Sắp Xếp:</span>
								<ul>
									<li>
										<span class="sorting_text">Giá từ cao đến thấp<i class="fas fa-chevron-down"></span></i>
										<ul>
											<a href="{{ route('rate_high') }}"><li class="shop_sorting_button" data-isotope-option='{ "sortBy": "original-order" }'>Giá từ cao đến thấp</li></a>
											<a href="{{ route('rate_low') }}"><li class="shop_sorting_button" data-isotope-option='{ "sortBy": "name" }'>Giá từ thấp đến cao</li></a>
											<a href="{{ route('rate_name') }}"><li class="shop_sorting_button"data-isotope-option='{ "sortBy": "price" }'>Tên</li></a>
										</ul>
									</li>
								</ul>
							</div>
						</div>

						<div class="product_grid">
							<div class="product_grid_border"></div>

							@foreach ($products as $product)

							<!-- Product Item -->
							<a href="{{ route('product.show',$product->id) }}">
							<div class="product_item is_new">
								<div class="product_border"></div>
								<div class="product_image d-flex flex-column align-items-center justify-content-center"><img src="{{ asset($product->img1) }}" alt=""></div>
								<div class="product_content">
									<div class="product_price"><?php echo number_format($product->price , 0, ',', '.'); ?> 
									<img src="{{ asset('images\vnd.png') }}" width='19px' style="margin-left: -5px">
									</div>
									<div class="product_name"><div><a href="#" tabindex="0">{{ $product->name }}</a></div></div>
									
								</div>
								<div class="product_fav"><i class="fas fa-heart"></i></div>
								<ul class="product_marks">
									<li class="product_mark product_discount">-25%</li>
									<li class="product_mark product_new">new</li>
								</ul>
								<div><a href="{!! route('index', [$product->id]) !!}">Thêm Giỏ Hàng</a></div>
							</div>
							</a>
							@endforeach

						</div>

						<!-- Shop Page Navigation -->

						<div class="shop_page_nav d-flex flex-row">
							
                			<div class="center">{!! $page->links() !!}</div>
							
						</div>

					</div>

				</div>
			</div>
		</div>
	</div>

	@endsection

resources/views/view.blade.php
<!DOCTYPE html>
<html lang="vi">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Tìm kiếm thông minh sử dụng Typeahead trong ứng dụng Laravel">
        <meta name="author" content="FirebirD ['www.allaravel.com']">
        <title>Tìm kiếm thông minh trong Laravel sử dụng Typeahead - Allaravel.com</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <style type="text/css">html{position:relative;min-height:100%;}body{margin-bottom:60px;}.footer{position:absolute;bottom:0;width:100%;height:60px;background-color:#f5f5f5;}body>.container{padding:60px 15px 0;}.container.text-muted{margin: 20px 0;}.footer>.container{padding-right:15px;padding-left:15px;}code{font-size:80%;}</style>
    </head>
    <body>
        <!-- Fixed navbar -->
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="https://allaravel.com">Typeahead</a>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="#">Home</a></li>
                        <li><a href="#about">About</a></li>
                        <li><a href="#contact">Contact</a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>

        <!-- Begin page content -->
        <div class="container">
            <div class="page-header">
                <h3>Ví dụ tìm kiếm thông minh sử dụng typeahead.js trong ứng dụng Laravel - Allaravel.com</h3>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <form class="form-inline typeahead">
                        <div class="form-group">
                            <input type="name" class="form-control search-input" id="name" autocomplete="off" placeholder="Nhập tên khách hàng">
                        </div>
                        <button type="submit" class="btn btn-default">Tìm kiếm</button>
                    </form>
                </div>
            </div>
        </div>

        <footer class="footer">
            <div class="container">
                <p class="text-muted">Example in <a href="https://allaravel.com">allaravel.com</a></p>
            </div>
        </footer>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.11.1/typeahead.bundle.min.js"></script>
        <script>
            jQuery(document).ready(function($) {
                var engine = new Bloodhound({
                    remote: {
                        url: 'api/customer?q=%QUERY%',
                        wildcard: '%QUERY%'
                    },
                    datumTokenizer: Bloodhound.tokenizers.whitespace('q'),
                    queryTokenizer: Bloodhound.tokenizers.whitespace
                });

                $(".search-input").typeahead({
                    hint: true,
                    highlight: true,
                    minLength: 1
                }, {
                    source: engine.ttAdapter(),
                    name: 'usersList',
                    templates: {
                        empty: [
                            '<div class="list-group search-results-dropdown"><div class="list-group-item">Không có kết quả phù hợp.</div></div>'
                        ],
                        header: [
                            '<div class="list-group search-results-dropdown">'
                        ],
                        suggestion: function (data) {
                            return '<a href="customer/' + data.id + '" class="list-group-item">' + data.name + '</a>'
                        }
                    }
                });
            });
        </script>
    </body>
</html>