routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

	
// Route::get('find', 'SearchController@find');
// Route::get('view', 'SearchController@view');
// Route::get('customer/{id}', function($id) {
//    $customer = App\Models\Admin\Customers::find($id);
//    return $customer->name . '@' . $customer->phone . '-' . $customer->address;
// });

// Route::get('autocomplete', 'SearchController@autocomplete');

Route::get('customer/{id}', function() {
   $customer = Customer::find($id);
   return $customer->name . '@' . $customer->phone . '-' . $customer->address;
});

Auth::routes();
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');


// Route::get('/home', 'HomeController@index')->name('home');

// Route::get('/', function () {
//     return view('layouts.index');
// });

	
// Admin
	Route::resource('categories_admin', 'Admin\Categories_AdminController');
	Route::resource('brand_admin', 'Admin\Brand_AdminController');
	Route::resource('status_admin', 'Admin\Status_AdminController');
	Route::resource('bill_admin', 'Admin\AdminBillController');
	Route::resource('user_admin', 'Admin\AdminUserController');
	Route::get('user_search_admin', 'Admin\AdminUserController@search')->name('user_search_admin');
	Route::get('userBlock_admin/{product_id}', 'Admin\AdminUserController@block')->name('userBlock_admin');
	Route::resource('profit', 'Admin\ProfitController');
	Route::get('invoice', 'Admin\ProfitController@invoice')->name('invoice');

	
	Route::resource('admin', 'Admin\DefaultController');
	Route::resource('status', 'StatusController');


	Route::resource('product_admin', 'Admin\Admin_ProductControlelr');
	Route::get('product_search_admin', 'Admin\Admin_ProductControlelr@search')->name('product_search_admin');
	Route::resource('shop_admin', 'Admin\AdminShopController');
	Route::get('shop_search_admin', 'Admin\AdminShopController@search')->name('shop_search_admin');
	Route::get('shop_admin_pay', 'Admin\AdminShopController@pay')->name('shop_admin_pay');
	Route::get('register_shop', 'Admin\AdminShopController@registerShop')->name('register_shop');
	Route::get('register_shop_details/{id}', 'Admin\AdminShopController@register_shop_details')->name('register_shop_details');
	Route::get('register_shop_update/{id}', 'Admin\AdminShopController@register_shop_update')->name('register_shop_update');
	Route::get('register_shop_destroy/{id}', 'Admin\AdminShopController@register_shop_destroy')->name('register_shop_destroy');


/*USER*/
	// USER
	Route::resource('user', 'UserController');
	Route::get('click/{email}', 'UserController@click')->name('click');
	Route::get('user_personalinformation/{id}', 'UserController@user_personalinformation')->name('user_personalinformation');
	Route::get('user_edit/{id}', 'UserController@user_personalinformation_edit')->name('user_edit');
	Route::PATCH('user_update/{id}', 'UserController@user_update')->name('user_update');

	Route::get('order', 'UserController@order')->name('order');
	Route::get('order_details/{id}', 'UserController@details')->name('order_details');

	Route::get('pay/{id}', 'UserController@pay')->name('pay');

	// SHOP
	Route::get('shop/{id}', 'UserController@shop')->name('shop');
	Route::get('shop_edit/{id}', 'UserController@shop_edit')->name('shop_edit');
	Route::get('shop_update/{id}', 'UserController@shop_update')->name('shop_update');
	Route::get('buy_post', 'UserController@buypost')->name('buy_post');
	Route::get('buy', 'UserController@buy')->name('buy');

	Route::resource('shop', 'ShopController');
	// PRODUCT
	Route::resource('product', 'ProductController');
	Route::get('star/{star}/{id}', 'ProductController@star')->name('star');
	Route::get('product_delete/{product_id}', 'ProductController@delete')->name('product_delete');
	Route::get('product_status/{product_id}/{status_id}', 'ProductController@status')->name('product_status');
	Route::get('product_search/{id}', 'ProductController@search')->name('product_search');
	//EXCHANGE
	Route::get('product_exchange', 'ProductController@exchange')->name('product_exchange');
	Route::get('month', 'ProductController@month')->name('month');

	Route::resource('comments', 'CommentController');
	Route::post('update_2/{cmt_id}/{product_id}', 'CommentController@update_2')->name('update_2');

	
/*RATE*/
	Route::resource('home', 'HomeController');
	Route::get('product_shop/{shop_id}', 'HomeController@product_shop')->name('product_shop');

	Route::get('search', 'HomeController@search')->name('search');

	Route::get('rate_high', 'HomeController@getRate_High')->name('rate_high');
	Route::get('rate_low', 'HomeController@getRate_Low')->name('rate_low');
	Route::get('rate_name', 'HomeController@getRate_Name')->name('rate_name');

/*CART*/
	Route::get('create_cart/{product_id}', 'CartController@create')->name('create_cart');
	Route::get('index/{product_id}', 'CartController@createIndex')->name('index');
	Route::get('cart', 'CartController@cart')->name('cart');
	Route::get('delete_cart/{id}', 'CartController@delete')->name('delete_cart');
	Route::get('deleteall_cart', 'CartController@deleteall')->name('deleteall_cart');
	// Route::post('update_cart/{id}/{increment}', 'CartController@update')->name('update_cart');
	Route::post('update_cart/{id}', 'CartController@update')->name('update_cart');
	Route::post('code_input/{id}', 'CartController@code')->name('code_input');

/*CHECKOUT*/
	Route::get('checkout/{id}', 'CartController@getCheckOut')->name('checkout');
	Route::post('post_checkout', 'CartController@postCheckOut')->name('post_checkout');
	Route::post('post_checkout_id/{id}', 'CartController@postCheckOut_id')->name('post_checkout_id');
	Route::post('post_checkout_code_id/{id}/{number}', 'CartController@postCheckOut_code_id')->name('post_checkout_code_id');


/*CATEGORIES*/
	Route::resource('categories', 'CategoriesController');

	/*ASIDE*/
	Route::get('categories_price/{categories_id}/{price1}/{price2}', 'CategoriesController@getCategories_Price')->name('categories_price');
	Route::get('categories_brand/{categories_id}/{brand_id}', 'CategoriesController@getCategorie_Brand')->name('categories_brand');
	Route::get('categories_price_brand/{categories_id}/{price1}/{price2}/{brand_id}', 'CategoriesController@getCategories_Price_Brand')->name('categories_price_brand');

	/*RATE: general*/
	Route::get('categories_rate_high/{categories_id}', 'CategoriesController@getCategories_RateHigh')->name('categories_ratehigh');
	Route::get('categories_rate_low/{categories_id}', 'CategoriesController@getCategories_RateLow')->name('categories_ratelow');
	Route::get('categories_rate_name/{categories_id}', 'CategoriesController@getCategories_RateName')->name('categories_ratename');

	/*RATE: price. no brand_id*/
	Route::get('categories_price_rate_high/{categories_id}/{price1}/{price2}', 'CategoriesController@getCategories_PriceRateHigh')->name('categories_price_ratehigh');
	Route::get('categories_price_rate_low/{categories_id}/{price1}/{price2}', 'CategoriesController@getCategories_PriceRateLow')->name('categories_price_ratelow');
	Route::get('categories_price_rate_name/{categories_id}/{price1}/{price2}', 'CategoriesController@getCategories_PriceRateName')->name('categories_price_ratename');

	/*RATE: no price. brand_id*/
	Route::get('categories_brand_rate_high/{categories_id}/{brand_id}', 'CategoriesController@getCategories_BrandRateHigh')->name('categories_brand_ratehigh');
	Route::get('categories_brand_rate_low/{categories_id}/{brand_id}', 'CategoriesController@getCategories_BrandRateLow')->name('categories_brand_ratelow');
	Route::get('categories_brand_rate_name/{categories_id}/{brand_id}', 'CategoriesController@getCategories_BrandRateName')->name('categories_brand_ratename');

	/*RATE: price. brand_id*/
	Route::get('categories_price_brand_rate_high/{categories_id}/{price1}/{price2}/{brand_id}', 'CategoriesController@getCategories_Price_BrandRateHigh')->name('categories_price_brand_ratehigh');
	Route::get('categories_price_brand_rate_low/{categories_id}/{price1}/{price2}/{brand_id}', 'CategoriesController@getCategorie_Price_BrandRateLow')->name('categories_price_brand_ratelow');
	Route::get('categories_price_brand_rate_name/{categories_id}/{price1}/{price2}/{brand_id}', 'CategoriesController@getCategories_Price_BrandRateName')->name('categories_price_brand_ratename');



/*BRAND*/
	Route::resource('brand', 'BrandController');

	/*ASIDE*/
	Route::get('brand_price/{brand_id}/{price1}/{price2}', 'BrandController@getBrand_Price')->name('brand_price');
	Route::get('brand_categories/{brand_id}/{categories_id}', 'BrandController@getBrand_Categories')->name('brand_categories');
	Route::get('brand_price_categories/{brand_id}/{price1}/{price2}/{categories_id}', 'BrandController@getBrand_Price_Categories')->name('brand_price_categories');

	/*RATE: general*/
	Route::get('brand_rate_high/{brand_id}', 'BrandController@getBrand_RateHigh')->name('brand_ratehigh');
	Route::get('brand_rate_low/{brand_id}', 'BrandController@getBrand_RateLow')->name('brand_ratelow');
	Route::get('brand_rate_name/{brand_id}', 'BrandController@getBrand_RateName')->name('brand_ratename');

	/*RATE: price. no categories*/
	Route::get('brand_price_rate_high/{brand_id}/{price1}/{price2}', 'BrandController@getBrand_PriceRateHigh')->name('brand_price_ratehigh');
	Route::get('brand_price_rate_low/{brand_id}/{price1}/{price2}', 'BrandController@getBrand_PriceRateLow')->name('brand_price_ratelow');
	Route::get('brand_price_rate_name/{brand_id}/{price1}/{price2}', 'BrandController@getBrand_PriceRateName')->name('brand_price_ratename');

	/*RATE: no price. categories_id*/

app/Http/Controllers/ShopController.php
<?php

namespace App\Http\Controllers;

use App\Models\Admin\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;


class ShopController extends Controller
{

    protected $user;



    public function __construct(User $user)
    {
        $this->user = $user;
        // $this->middleware('auth');
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        return view('shop.shop', compact('user'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(user $user)
    {
       
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/shop/shop.blade.php
@extends('inc-index/layout')
<script src="{{ asset('js/jquery-3.3.1.min.js')}}"></script>
<script src="{{ asset('js/custom.js ')}}"></script>
@section('content')
   
   <style type="text/css">
       .table-nam {
                width: 100%;
                margin-left: 200px; 
                max-width: 60%;
                margin-bottom: 1rem;
                background-color: transparent;
       }

       .table-nam td {
            padding: .75rem;
       }
   </style>
    <div class="shop">
        <div class="container">
            <div class="row">

                <div class="col-lg-3"  style="border-right: 1px solid #eee">

                  
                <div class="list-group">
                    <a href="#" class="list-group-item list-group-item-action active">
                    TỔNG QUAN
                    </a>
                    <a class="sidebar_title list-group-item list-group-item-action" href=" {{ route('user.index') }}">Thông Tin Tài Khoản</a>
                    <a class="sidebar_title list-group-item list-group-item-action" href=" {{ route('order') }}">Đơn Hàng</a>
                    <a class="sidebar_title list-group-item list-group-item-action" href=" {{ route('shop.index') }}"">Danh Sách Sản Phẩm</a>
                    <a class="sidebar_title list-group-item list-group-item-action" href=" {{ route('product.create') }}"">Đăng Sản Phẩm</a>
                    <!--  -->
                 
                    </div>
                </div>
                <div class="col-lg-9">
                        <div class="box">
            <div class="box-header">
              <h3 class="box-title">Sản Phẩm</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
            <table id="example2" class="table table-bordered table-hover">
                        <thead>
                        <tr>
                            <th class="text-center">STT</th>
                            <th class="text-center">name</th>
                            <th class="text-center">price</th>
                            <th class="text-center">review</th>
                            <th class="text-center">img</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                            <?php $i = 1 ?>
                        @foreach ($products as $product)
                        <tr>
                            <td>{{ $i++ }}</td>
                            <td>{{ $product->name}}</td>
                            <td>{{ $product->price }} Đ</td>
                            <td width="300px" height="100px">{!! $product->review !!}</td>
                            <td><img src="{{ $product->img1 }}  "></td>
                            <td>
                                {!! Form::open(array('route'=> ['product.destroy', $product->id], 'method' => 'DELETE')) !!}
                                    {{ link_to_route('product.edit', 'Sửa', [$product->id], ['class' => 'btn btn-primary btn-xs btn-block']) }}
                                
                                    {!! Form::button('Xóa', ['class' => 'btn btn-danger btn-xs btn-block', 'type' => 'submit']) !!}                    
                                {!! Form::close() !!}
                            </td>
                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                            <div class="center">{!! $products->links() !!}</div>
                        <div class="clearfix visible-sm-block"></div>
                     </div>
            </div>
        </div>
    </div>
                    </div>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                        <!-- Shop Page Navigation -->

                        <div class="shop_page_nav d-flex flex-row">
                            
                            
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>

@endsection