routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

	
// Route::get('find', 'SearchController@find');
// Route::get('view', 'SearchController@view');
// Route::get('customer/{id}', function($id) {
//    $customer = App\Models\Admin\Customers::find($id);
//    return $customer->name . '@' . $customer->phone . '-' . $customer->address;
// });

// Route::get('autocomplete', 'SearchController@autocomplete');

Route::get('customer/{id}', function() {
   $customer = Customer::find($id);
   return $customer->name . '@' . $customer->phone . '-' . $customer->address;
});

Auth::routes();
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');


// Route::get('/home', 'HomeController@index')->name('home');

// Route::get('/', function () {
//     return view('layouts.index');
// });

	
// Admin
	Route::resource('categories_admin', 'Admin\Categories_AdminController');
	Route::resource('brand_admin', 'Admin\Brand_AdminController');
	Route::resource('status_admin', 'Admin\Status_AdminController');
	Route::resource('bill_admin', 'Admin\AdminBillController');
	Route::resource('user_admin', 'Admin\AdminUserController');
	Route::get('user_search_admin', 'Admin\AdminUserController@search')->name('user_search_admin');
	Route::get('userBlock_admin/{product_id}', 'Admin\AdminUserController@block')->name('userBlock_admin');
	Route::resource('profit', 'Admin\ProfitController');
	Route::get('invoice', 'Admin\ProfitController@invoice')->name('invoice');

	
	Route::resource('admin', 'Admin\DefaultController');
	Route::resource('status', 'StatusController');


	Route::resource('product_admin', 'Admin\Admin_ProductControlelr');
	Route::get('product_search_admin', 'Admin\Admin_ProductControlelr@search')->name('product_search_admin');
	Route::resource('shop_admin', 'Admin\AdminShopController');
	Route::get('shop_search_admin', 'Admin\AdminShopController@search')->name('shop_search_admin');
	Route::get('shop_admin_pay', 'Admin\AdminShopController@pay')->name('shop_admin_pay');
	Route::get('register_shop', 'Admin\AdminShopController@registerShop')->name('register_shop');
	Route::get('register_shop_details/{id}', 'Admin\AdminShopController@register_shop_details')->name('register_shop_details');
	Route::get('register_shop_update/{id}', 'Admin\AdminShopController@register_shop_update')->name('register_shop_update');
	Route::get('register_shop_destroy/{id}', 'Admin\AdminShopController@register_shop_destroy')->name('register_shop_destroy');


/*USER*/
	// USER
	Route::resource('user', 'UserController');
	Route::get('click/{email}', 'UserController@click')->name('click');
	Route::get('user_personalinformation/{id}', 'UserController@user_personalinformation')->name('user_personalinformation');
	Route::get('user_edit/{id}', 'UserController@user_personalinformation_edit')->name('user_edit');
	Route::PATCH('user_update/{id}', 'UserController@user_update')->name('user_update');

	Route::get('order', 'UserController@order')->name('order');
	Route::get('order_details/{id}', 'UserController@details')->name('order_details');

	Route::get('pay/{id}', 'UserController@pay')->name('pay');

	// SHOP
	Route::get('shop/{id}', 'UserController@shop')->name('shop');
	Route::get('shop_edit/{id}', 'UserController@shop_edit')->name('shop_edit');
	Route::get('shop_update/{id}', 'UserController@shop_update')->name('shop_update');
	Route::get('buy_post', 'UserController@buypost')->name('buy_post');
	Route::get('buy', 'UserController@buy')->name('buy');

	Route::resource('shop', 'ShopController');
	// PRODUCT
	Route::resource('product', 'ProductController');
	Route::get('star/{star}/{id}', 'ProductController@star')->name('star');
	Route::get('product_delete/{product_id}', 'ProductController@delete')->name('product_delete');
	Route::get('product_status/{product_id}/{status_id}', 'ProductController@status')->name('product_status');
	Route::get('product_search/{id}', 'ProductController@search')->name('product_search');
	//EXCHANGE
	Route::get('product_exchange', 'ProductController@exchange')->name('product_exchange');
	Route::get('month', 'ProductController@month')->name('month');

	Route::resource('comments', 'CommentController');
	Route::post('update_2/{cmt_id}/{product_id}', 'CommentController@update_2')->name('update_2');

	
/*RATE*/
	Route::resource('home', 'HomeController');
	Route::get('product_shop/{shop_id}', 'HomeController@product_shop')->name('product_shop');

	Route::get('search', 'HomeController@search')->name('search');

	Route::get('rate_high', 'HomeController@getRate_High')->name('rate_high');
	Route::get('rate_low', 'HomeController@getRate_Low')->name('rate_low');
	Route::get('rate_name', 'HomeController@getRate_Name')->name('rate_name');

/*CART*/
	Route::get('create_cart/{product_id}', 'CartController@create')->name('create_cart');
	Route::get('index/{product_id}', 'CartController@createIndex')->name('index');
	Route::get('cart', 'CartController@cart')->name('cart');
	Route::get('delete_cart/{id}', 'CartController@delete')->name('delete_cart');
	Route::get('deleteall_cart', 'CartController@deleteall')->name('deleteall_cart');
	// Route::post('update_cart/{id}/{increment}', 'CartController@update')->name('update_cart');
	Route::post('update_cart/{id}', 'CartController@update')->name('update_cart');
	Route::post('code_input/{id}', 'CartController@code')->name('code_input');

/*CHECKOUT*/
	Route::get('checkout/{id}', 'CartController@getCheckOut')->name('checkout');
	Route::post('post_checkout', 'CartController@postCheckOut')->name('post_checkout');
	Route::post('post_checkout_id/{id}', 'CartController@postCheckOut_id')->name('post_checkout_id');
	Route::post('post_checkout_code_id/{id}/{number}', 'CartController@postCheckOut_code_id')->name('post_checkout_code_id');


/*CATEGORIES*/
	Route::resource('categories', 'CategoriesController');

	/*ASIDE*/
	Route::get('categories_price/{categories_id}/{price1}/{price2}', 'CategoriesController@getCategories_Price')->name('categories_price');
	Route::get('categories_brand/{categories_id}/{brand_id}', 'CategoriesController@getCategorie_Brand')->name('categories_brand');
	Route::get('categories_price_brand/{categories_id}/{price1}/{price2}/{brand_id}', 'CategoriesController@getCategories_Price_Brand')->name('categories_price_brand');

	/*RATE: general*/
	Route::get('categories_rate_high/{categories_id}', 'CategoriesController@getCategories_RateHigh')->name('categories_ratehigh');
	Route::get('categories_rate_low/{categories_id}', 'CategoriesController@getCategories_RateLow')->name('categories_ratelow');
	Route::get('categories_rate_name/{categories_id}', 'CategoriesController@getCategories_RateName')->name('categories_ratename');

	/*RATE: price. no brand_id*/
	Route::get('categories_price_rate_high/{categories_id}/{price1}/{price2}', 'CategoriesController@getCategories_PriceRateHigh')->name('categories_price_ratehigh');
	Route::get('categories_price_rate_low/{categories_id}/{price1}/{price2}', 'CategoriesController@getCategories_PriceRateLow')->name('categories_price_ratelow');
	Route::get('categories_price_rate_name/{categories_id}/{price1}/{price2}', 'CategoriesController@getCategories_PriceRateName')->name('categories_price_ratename');

	/*RATE: no price. brand_id*/
	Route::get('categories_brand_rate_high/{categories_id}/{brand_id}', 'CategoriesController@getCategories_BrandRateHigh')->name('categories_brand_ratehigh');
	Route::get('categories_brand_rate_low/{categories_id}/{brand_id}', 'CategoriesController@getCategories_BrandRateLow')->name('categories_brand_ratelow');
	Route::get('categories_brand_rate_name/{categories_id}/{brand_id}', 'CategoriesController@getCategories_BrandRateName')->name('categories_brand_ratename');

	/*RATE: price. brand_id*/
	Route::get('categories_price_brand_rate_high/{categories_id}/{price1}/{price2}/{brand_id}', 'CategoriesController@getCategories_Price_BrandRateHigh')->name('categories_price_brand_ratehigh');
	Route::get('categories_price_brand_rate_low/{categories_id}/{price1}/{price2}/{brand_id}', 'CategoriesController@getCategorie_Price_BrandRateLow')->name('categories_price_brand_ratelow');
	Route::get('categories_price_brand_rate_name/{categories_id}/{price1}/{price2}/{brand_id}', 'CategoriesController@getCategories_Price_BrandRateName')->name('categories_price_brand_ratename');



/*BRAND*/
	Route::resource('brand', 'BrandController');

	/*ASIDE*/
	Route::get('brand_price/{brand_id}/{price1}/{price2}', 'BrandController@getBrand_Price')->name('brand_price');
	Route::get('brand_categories/{brand_id}/{categories_id}', 'BrandController@getBrand_Categories')->name('brand_categories');
	Route::get('brand_price_categories/{brand_id}/{price1}/{price2}/{categories_id}', 'BrandController@getBrand_Price_Categories')->name('brand_price_categories');

	/*RATE: general*/
	Route::get('brand_rate_high/{brand_id}', 'BrandController@getBrand_RateHigh')->name('brand_ratehigh');
	Route::get('brand_rate_low/{brand_id}', 'BrandController@getBrand_RateLow')->name('brand_ratelow');
	Route::get('brand_rate_name/{brand_id}', 'BrandController@getBrand_RateName')->name('brand_ratename');

	/*RATE: price. no categories*/
	Route::get('brand_price_rate_high/{brand_id}/{price1}/{price2}', 'BrandController@getBrand_PriceRateHigh')->name('brand_price_ratehigh');
	Route::get('brand_price_rate_low/{brand_id}/{price1}/{price2}', 'BrandController@getBrand_PriceRateLow')->name('brand_price_ratelow');
	Route::get('brand_price_rate_name/{brand_id}/{price1}/{price2}', 'BrandController@getBrand_PriceRateName')->name('brand_price_ratename');

	/*RATE: no price. categories_id*/

resources/views/admin/inc/aside.blade.php
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="{{ asset('dist/img/avatar.png') }}" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>{{ Auth::user()->name }}</p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>
      <!-- search form -->
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Tìm Kiếm...">
          <span class="input-group-btn">
            <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
            </button>
          </span>
        </div>
      </form>
      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">Trang chủ</li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-pie-chart"></i>
            <span>Danh mục thể loại</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
              <li><a href=" {{ route('categories_admin.index') }} "><i class="fa fa-circle-o"></i>Danh sách thể loại</a></li>
            <li><a href=" {{ route('categories_admin.create') }} "><i class="fa fa-circle-o"></i>Thêm danh mục thể loại</a></li>
          </ul>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-users"></i>
            <span>sản phẩm</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href=" {{ route('product_admin.index') }} "><i class="fa fa-circle-o"></i>Danh sách sản phẩm</a></li>
            <!-- <li><a href=" {{ route('product.create') }} "><i class="fa fa-circle-o"></i>Thêm sản phẩm</a></li> -->
          </ul>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-files-o"></i> <span>Hãng sx</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
           <li><a href=" {{ route('brand_admin.index') }} "><i class="fa fa-circle-o"></i>Danh sách hãng</a></li>
            <li><a href=" {{ route('brand_admin.create') }} "><i class="fa fa-circle-o"></i>Thêm hãng</a></li>
          </ul>
        </li>

        <li class="treeview">
          <a href="#">
            <i class="fa fa-google-plus"></i> <span>Thành viên</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href=" {{ route('user_admin.index') }} "><i class="fa fa-circle-o"></i>Quản lý thành viên</a></li>
            <!-- <li><a href=" {{ route('user.create') }} "><i class="fa fa-circle-o"></i>Thêm thành viên</a></li> -->
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-google-plus"></i> <span>Shop</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
              <li><a href=" {{ route('shop_admin.index') }} "><i class="fa fa-circle-o"></i>Quản lý Shop</a></li>
              <li><a href=" {{ route('bill_admin.index') }} "><i class="fa fa-circle-o"></i>Chi tiết đơn hàng</a></li>
              <li><a href=" {{ route('shop_admin_pay') }} "><i class="fa fa-circle-o"></i>Yêu cầu thanh toán</a></li>
              <li><a href=" {{ route('register_shop') }} "><i class="fa fa-circle-o"></i>Đăng ký cửa hàng</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-pie-chart"></i> <span>Thống Kê</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
              <li><a href=" {{ route('profit.index') }} "><i class="fa fa-circle-o"></i>Thống Kê</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-google-plus"></i> <span>Tin Tức</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href=" {{ route('information.index') }} "><i class="fa fa-circle-o"></i>Quản lý Tin Tức</a></li>
            <li><a href=" {{ route('information.create') }} "><i class="fa fa-circle-o"></i>Thêm tin tức</a></li>
            <!-- <li><a href=" {{ route('user.create') }} "><i class="fa fa-circle-o"></i>Thêm thành viên</a></li> -->
          </ul>
        </li>

      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->

resources/views/admin/inc/footer.blade.php
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 2.4.0
    </div>
    <strong>Copyright &copy; 2014-2016 <a href="https://adminlte.io">Almsaeed Studio</a>.</strong> All rights
    reserved.
  </footer>

resources/views/admin/inc/index.blade.php
@extends('admin.inc.layouts')
@section('content')

    <!-- Main content -->
    <section class="content">
      <section class="content-header">
      <h1>
        Chào mừng bạn đến với trang quản trị website
      </h1>
    </section>
    <br>
      <!-- Info boxes -->
      <div class="row">
         <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-aqua"><i class="fa fa-fw fa-paw"></i></span>

            <div class="info-box-content">
              <span class="info-box-text">Thành viên</span>
              <span class="info-box-number">{!! $count_user !!}<small></small></span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        <!-- /.col -->
        <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-yellow"><i class="fa fa-fw fa-reorder"></i></span>

            <div class="info-box-content">
              <span class="info-box-text">Danh mục sản phẩm</span>
              <span class="info-box-number">{!! $count_categories !!}<small></small></span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        <!-- /.col -->
        <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-aqua"><i class="ion ion-ios-gear-outline"></i></span>

            <div class="info-box-content">
              <span class="info-box-text">Sản phẩm</span>
              <span class="info-box-number">{!! $count_product !!}<small></small></span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        <!-- /.col -->
         <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-green"><i class="ion ion-ios-cart-outline"></i></span>

            <div class="info-box-content">
              <span class="info-box-text">Đơn hàng</span>
              <span class="info-box-number">{!! $count_customer !!}</span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        <!-- /.col -->
         <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-aqua"><i class="ion ion-ios-cart-outline"></i></span>

            <div class="info-box-content">
              <span class="info-box-text">Đơn hàng Chưa Xử Lý</span>
              <span class="info-box-number">{!! $customerInfosCXL !!}</span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-green"><i class="fa fa-fw fa-ship"></i></span>

            <div class="info-box-content">
              <span class="info-box-text">Nhà sản xuất</span>
              <span class="info-box-number">{!! $count_brand !!}</span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        <!-- /.col -->
         <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-aqua"><i class="fa fa-fw fa-reorder"></i></span>

            <div class="info-box-content">
              <span class="info-box-text">Danh mục tin tức </span>
              <span class="info-box-number">4<small></small></span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        <!-- /.col -->
         <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-yellow"><i class="fa fa-fw fa-pencil-square-o"></i></span>

            <div class="info-box-content">
              <span class="info-box-text">Bài viết</span>
              <span class="info-box-number">{{ $count_information }}<small></small></span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        
         
        <!-- /.col -->

        <!-- fix for small devices only -->
        <div class="clearfix visible-sm-block"></div>

     
      </div>
      <!-- /.row -->

     
    

     
      
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
@endsection

resources/views/admin/inc/layouts.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>@yield('title', 'Admin')</title>
   <link rel="SHORTCUT ICON" href="{{asset('img/logo.png')}}" type="image/x-icon">
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  @include('admin.inc.style')
  @yield('css')
</head>
<body class="hold-transition skin-blue sidebar-mini" style="font-style: italic;">
<!-- Site wrapper -->
<div class="wrapper">

  @include('admin.inc.header')


  <!-- Left side column. contains the sidebar -->
  @include('admin.inc.aside')

  <!-- =============================================== -->

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      
      <ol class="breadcrumb">
        <li><a href="{{ route('admin.index') }}"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <!-- <li class="active">Dashboard</li> -->
      </ol>
    </section>
<br>
    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
        @yield('header')    
        @yield('content') 
        @yield('footer')
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  @include('admin.inc.footer')
  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
      <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>

      <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
      <!-- Home tab content -->
      <div class="tab-pane" id="control-sidebar-home-tab">
        <h3 class="control-sidebar-heading">Recent Activity</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-birthday-cake bg-red"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                <p>Will be 23 on April 24th</p>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-user bg-yellow"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

                <p>New phone +1(800)555-1234</p>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

                <p>nora@example.com</p>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-file-code-o bg-green"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

                <p>Execution time 5 seconds</p>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

        <h3 class="control-sidebar-heading">Tasks Progress</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Custom Template Design
                <span class="label label-danger pull-right">70%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Update Resume
                <span class="label label-success pull-right">95%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-success" style="width: 95%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Laravel Integration
                <span class="label label-warning pull-right">50%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Back End Framework
                <span class="label label-primary pull-right">68%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

      </div>
      <!-- /.tab-pane -->
      <!-- Stats tab content -->
      <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
      <!-- /.tab-pane -->
      <!-- Settings tab content -->
      <div class="tab-pane" id="control-sidebar-settings-tab">
        <form method="post">
          <h3 class="control-sidebar-heading">General Settings</h3>

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Report panel usage
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Some information about this general settings option
            </p>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Allow mail redirect
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Other sets of options are available
            </p>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Expose author name in posts
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Allow the user to show his name in blog posts
            </p>
          </div>
          <!-- /.form-group -->

          <h3 class="control-sidebar-heading">Chat Settings</h3>

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Show me as online
              <input type="checkbox" class="pull-right" checked>
            </label>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Turn off notifications
              <input type="checkbox" class="pull-right">
            </label>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Delete chat history
              <a href="javascript:void(0)" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
            </label>
          </div>
          <!-- /.form-group -->
        </form>
      </div>
      <!-- /.tab-pane -->
    </div>
  </aside>
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->
@include('admin.inc.javascript')
@yield('js')
</body>
</html>